services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  init:
    build:
      context: ./init
    command: python init_dynamo.py
    environment:
      - TABLE_NAME=jobs
      - ENV=development
      - AWS_DEFAULT_REGION=us-east-1

  submitter:
    build:
      context: ./submitter
    command: python app.py
    ports: 
      - "127.0.0.1:5000:5000"

