services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  init:
    volumes:
        - ~/.aws:/root/.aws
    build:
      context: .
      dockerfile: init/Dockerfile
    command: python init_dynamo.py
    environment:
      - TABLE_NAME=jobs
      - ENV=development
      - AWS_DEFAULT_REGION=us-east-1

  submitter:
    volumes:
      - ~/.aws:/root/.aws
    build:
      dockerfile: submitter/Dockerfile
      context: .
    command: python app.py
    ports: 
      - "127.0.0.1:5000:5000"
    environment:
      - TABLE_NAME=jobs
      - ENV=development
      - AWS_DEFAULT_REGION=us-east-1
    

